// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Helltale/amdm-guitar-chords/back/internal/repository (interfaces: SongRepository)
//
// Generated by this command:
//
//	mockgen -package=testdata -destination=./testdata/song_repo_mock.go github.com/Helltale/amdm-guitar-chords/back/internal/repository SongRepository
//

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	entity "github.com/Helltale/amdm-guitar-chords/back/internal/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSongRepository is a mock of SongRepository interface.
type MockSongRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSongRepositoryMockRecorder
	isgomock struct{}
}

// MockSongRepositoryMockRecorder is the mock recorder for MockSongRepository.
type MockSongRepositoryMockRecorder struct {
	mock *MockSongRepository
}

// NewMockSongRepository creates a new mock instance.
func NewMockSongRepository(ctrl *gomock.Controller) *MockSongRepository {
	mock := &MockSongRepository{ctrl: ctrl}
	mock.recorder = &MockSongRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSongRepository) EXPECT() *MockSongRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSongRepository) Create(ctx context.Context, s *entity.Song) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSongRepositoryMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSongRepository)(nil).Create), ctx, s)
}

// GetByArtistIDAndSlug mocks base method.
func (m *MockSongRepository) GetByArtistIDAndSlug(ctx context.Context, artistID uuid.UUID, slug string) (*entity.Song, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByArtistIDAndSlug", ctx, artistID, slug)
	ret0, _ := ret[0].(*entity.Song)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByArtistIDAndSlug indicates an expected call of GetByArtistIDAndSlug.
func (mr *MockSongRepositoryMockRecorder) GetByArtistIDAndSlug(ctx, artistID, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByArtistIDAndSlug", reflect.TypeOf((*MockSongRepository)(nil).GetByArtistIDAndSlug), ctx, artistID, slug)
}

// GetByID mocks base method.
func (m *MockSongRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Song, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Song)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSongRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSongRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockSongRepository) List(ctx context.Context, artistID *uuid.UUID, limit, offset int, sort string) ([]*entity.Song, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, artistID, limit, offset, sort)
	ret0, _ := ret[0].([]*entity.Song)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockSongRepositoryMockRecorder) List(ctx, artistID, limit, offset, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSongRepository)(nil).List), ctx, artistID, limit, offset, sort)
}

// ListByArtistID mocks base method.
func (m *MockSongRepository) ListByArtistID(ctx context.Context, artistID uuid.UUID) ([]*entity.Song, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByArtistID", ctx, artistID)
	ret0, _ := ret[0].([]*entity.Song)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByArtistID indicates an expected call of ListByArtistID.
func (mr *MockSongRepositoryMockRecorder) ListByArtistID(ctx, artistID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByArtistID", reflect.TypeOf((*MockSongRepository)(nil).ListByArtistID), ctx, artistID)
}

// Search mocks base method.
func (m *MockSongRepository) Search(ctx context.Context, query string, limit, offset int) ([]*entity.Song, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, limit, offset)
	ret0, _ := ret[0].([]*entity.Song)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockSongRepositoryMockRecorder) Search(ctx, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSongRepository)(nil).Search), ctx, query, limit, offset)
}

// Update mocks base method.
func (m *MockSongRepository) Update(ctx context.Context, s *entity.Song) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSongRepositoryMockRecorder) Update(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSongRepository)(nil).Update), ctx, s)
}
